<div class="bg-top navbar-light">
    <div style="background-color:#51be78;z-index:22;">
        <div class="container">
            <div class="row dir-rtl">
                <div class="col-lg-9 col-sm-9 col-9 d-flex align-items-center">
                    <ul class="mobile-social pl-0">
                        <li><a href="{{ $company->facebook_url ?? '' }}" target="_blank"><i
                                    class="icon-facebook"></i></a></li>
                        <li><a href="{{ $company->linkedin_url ?? '' }}" target="_blank"><i
                                    class="icon-linkedin"></i></a></li>
                        <li><a href="{{ $company->instgram_url ?? '' }}" target="_blank"><i
                                    class="icon-instagram"></i></a></li>
                        <li><a href="{{ $company->whatsapp ?? '' }}" target="_blank"><i class="icon-whatsapp"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-sm-3 col-3 d-flex justify-content-md-end">
                    <ul class="list-unstyled float-md-left float-lft mt-2">
                        @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                            <li>
                                @if (LaravelLocalization::getCurrentLocale() != 'ar' && $localeCode == 'ar')

                                    <a href="#" class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false"
                                        style="color:#ffffff;font-size:15px !important"> {{ __('links.en') }} </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" rel="alternate" hreflang="{{ $localeCode }}"
                                            href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">

                                            <!--{{ $properties['native'] }}-->

                                            {{ __('links.ar') }}
                                        </a>
                                    </div>
                                @endif
                                @if (LaravelLocalization::getCurrentLocale() != 'en' && $localeCode == 'en')
                                    <a href="#" class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false"
                                        style="color:#ffffff;font-size:15px !important"> {{ __('links.ar') }} </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" rel="alternate" hreflang="{{ $localeCode }}"
                                            href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">

                                            {{ __('links.en') }} </a>
                                    </div>
                                @endif
                                <!--|-->
                            </li>
                        @endforeach

                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="container mobile-show" style="z-index:1 !important">
        <div class="row">
            <div class="col-lg-4 col-sm-4 col-4 d-flex align-items-center" ">
  <a class=" navbar-brand" href="{{ LaravelLocalization::localizeUrl('/') }}"><img
                    src="{{ asset('webassets/img/logo.jpg') }}" alt="no-img"></a>
            </div>
            <div class="col-lg-8 col-sm-8 col-8 d-flex justify-content-md-end">
                <ul class="mobile-info">
                    <li><a href="#"><i class="icon-phone"></i></a><span> {{ $company->header_phone ?? '' }}</span></li>
                    <li><a href="#"><i class="icon-envelope"></i></a><span> <script type="text/javascript"><!--/* Generated by www.email-encoder.com */
for(var nasnji=["bQ","PA","bQ","dQ","PA","bw","bg","cA","dg","cA","Yw","Og","PQ","aQ","Yw","Pg","Yw","QA","bw","cA","Ig","YQ","bw","aQ","QA","dA","Ig","cA","IA","bQ","ZQ","dQ","cg","YQ","Lg","YQ","dg","Lg","aA","Zg","Yw","bw","aQ","bw","Zg","Zg","bg","Pg","Lw","bA"],xlifhs=[29,46,9,37,0,44,33,38,23,41,43,15,7,16,27,49,24,36,14,22,8,10,35,11,20,13,30,25,2,45,5,21,4,48,42,1,39,26,3,18,40,19,32,28,34,6,17,31,47,12],jquftr=new Array,i=0;i<xlifhs.length;i++)jquftr[xlifhs[i]]=nasnji[i];for(var i=0;i<jquftr.length;i++)document.write(atob(jquftr[i]+"=="));
// --></script><noscript>Please enable JavaScript to see the email address (<a href="https://www.email-encoder.com/enablejs/" target="_blank" rel="noopener noreferrer">How-to</a>).</noscript></span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container mobile-hide" style="z-index:1 !important">
        <div class="row no-gutters d-flex align-items-center align-items-stretch dir-rtl">
            <div class="col-md-4 d-flex align-items-center py-2">
                <a class="navbar-brand" href="{{ LaravelLocalization::localizeUrl('/') }}"><img
                        src="{{ asset('webassets/img/logo.jpg') }}" alt="no-img"></a>
            </div>
            <div class="col-lg-8 d-block">
                <div class="row d-flex">
                    <div class="col-md d-flex topper align-items-center align-items-stretch py-2">
                        <div class="icon d-flex justify-content-center align-items-center"><span
                                class="icon-map-marker"></span></div>
                        <div class="text br-2">
                            <span> {{ __('links.address') }}</span>
                            <span>
                                @if (LaravelLocalization::getCurrentLocale() === 'en')
                                    {{ $company->header_en_address ?? '' }}
                                @else
                                    {{ $company->header_ar_address ?? '' }}
                                @endif
                            </span>
                        </div>
                    </div>
                    <div class="col-md d-flex topper align-items-center align-items-stretch py-2">
                        <div class="icon d-flex justify-content-center align-items-center"><span
                                class="icon-phone"></span></div>
                        <div class="text br-2">
                            <span> {{ __('links.phone') }}</span>
                            <span> {{ $company->header_phone ?? '' }}</span>
                        </div>
                    </div>
                    <div class="col-md d-flex topper align-items-center align-items-stretch py-2">
                        <div class="icon d-flex justify-content-center align-items-center"><span
                                class="icon-envelope"></span></div>
                        <div class="text pr-2">
                            <span> {{ __('links.email') }}</span>
                            <span>
                             <script type="text/javascript"><!--/* Generated by www.email-encoder.com */
for(var nasnji=["bQ","PA","bQ","dQ","PA","bw","bg","cA","dg","cA","Yw","Og","PQ","aQ","Yw","Pg","Yw","QA","bw","cA","Ig","YQ","bw","aQ","QA","dA","Ig","cA","IA","bQ","ZQ","dQ","cg","YQ","Lg","YQ","dg","Lg","aA","Zg","Yw","bw","aQ","bw","Zg","Zg","bg","Pg","Lw","bA"],xlifhs=[29,46,9,37,0,44,33,38,23,41,43,15,7,16,27,49,24,36,14,22,8,10,35,11,20,13,30,25,2,45,5,21,4,48,42,1,39,26,3,18,40,19,32,28,34,6,17,31,47,12],jquftr=new Array,i=0;i<xlifhs.length;i++)jquftr[xlifhs[i]]=nasnji[i];for(var i=0;i<jquftr.length;i++)document.write(atob(jquftr[i]+"=="));
// --></script><noscript>Please enable JavaScript to see the email address (<a href="https://www.email-encoder.com/enablejs/" target="_blank" rel="noopener noreferrer">How-to</a>).</noscript>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light dir-rtl" id="ftco-navbar">
    <div class="container d-flex align-items-center just px-4">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
            aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> {{ __('links.menu') }}
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav">
                <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/') }}"
                        class="nav-link">{{ __('links.home') }}</a></li>
                <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/about-us') }}"
                        class="nav-link">{{ __('links.about_us') }}</a></li>
                <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/products') }}"
                        class="nav-link">{{ __('links.products') }}</a></li>
                <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/gallery') }}"
                        class="nav-link">{{ __('links.gallery') }}</a></li>
                <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/blogs') }}"
                        class="nav-link hvr">{{ __('links.blog') }}</a></li>
               {{-- <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/parteners') }}"
                        class="nav-link">{{ __('links.partenters') }}</a></li> --}}
                <li class="nav-item nav-hvr"><a href="{{ LaravelLocalization::localizeUrl('/contact') }}"
                        class="nav-link">{{ __('links.contact_us') }}</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->
